### ISSUE TITLE
I can not import the module

### ISSUE THREAD

**Issue by elib0** [radyushin/vue-localstorage#2]
ES6:
``
import VueLocalStorage from 'vue-local-storage'
``

**Comment by SmirnovW** [comment]
@elib0 Hello! Sorry me for a long answer :( I hope it's not too late. Let me show you how I do an import. At first, I use webpack 2, this is my config:

```
const path = require('path');

module.exports = {
	entry: './app.js',
	output: {
		filename: './bundle.js'
	},
	module: {
		rules: [
			{
				test: /\.js$/,
				use: [{
					loader: 'babel-loader'
				}],
			},
		],
	},
	resolve: {
		modules: [
			path.resolve('./node_modules')
		]
	}  
};

```
and in my app.js:

```
import VueLocalStorage from 'vue-localstorage'

console.log(VueLocalStorage)
```

this works for me as well.
Can you tell me how exactly you try do import and what kind of tools you are using?

**Comment by SmirnovW** [comment]
By the way, you have an error in your code 

`import VueLocalStorage from 'vue-local-storage'`

should be: `import VueLocalStorage from 'vue-localstorage'`
